language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
    - pip install -r requirements.txt
    - pip install -U nose2 codecov cov-core coverage

script: make coverage
after_success: codecov

notifications:
  webhooks:
    urls:
      - $GITTER_NOTIFICATION_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
