BEGIN:VCARD
VERSION:2.1
N:{{lastname}};{{firstname}};;;
FN:{{fullname}}
ORG:{{company}}
TITLE:{{jobtitle}}
TEL;WORK;VOICE:{{phone}}
ADR;WORK:;;{{adress}};{{city}};{{state}};{{zipcode}};{{country}}
EMAIL;PREF;INTERNET:{{email}}
UID:urn:uuid:{{guid}}
URL:{{homepage}}
GENDER:{{gender|upper}}
END:VCARD
